apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: kishore-azure-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-secret
      key: creds
