apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-crossplane-idp
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/kishore-behera/fluxcd-crossplane-idp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mdp-helm-template
  namespace: flux-system
spec:
  interval: 1m
  path: "./crossplane-resources/mdp-poc"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
