apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm/crossplane-helmrelease.yaml
  - helm/crossplane-helmrepository.yaml
  - secrets/sealed-azure-secret.yaml
  - azure-provider/provider-config.yaml
  - azure-provider/provider-azure-network.yaml
  - azure-provider/provider-azure-management.yaml
  - azure-provider/provider-azure-cosmosdb.yaml
  - azure-provider/provider-azure-dbforpostgresql.yaml
  - azure-provider/provider-azure-storage.yaml
  # - azure-provider/provider-azure-image.yaml
  - azure-provider/provider-azure-authorization.yaml
  - azure-provider/provider-azure-azuread.yaml
  - azure-provider/provider-azure-compute.yaml
  - azure-provider/provider-azure-managedidentity.yaml
  - azure-provider/provider-azure-provider-azure.yaml
  - azure-provider/provider-azure-containerservice.yaml
