{{- if .Values.kubernetesClusters }}
{{- range .Values.kubernetesClusters }}
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: {{ .name }}
spec:
  providerConfigRef:
    name: {{ .providerConfigRefName }}
  forProvider:
    location: {{ .location }}
    resourceGroupName: {{ .resourceGroupName }}
    kubernetesVersion: {{ .kubernetesVersion }}
    privateClusterEnabled: {{ .privateClusterEnabled }}
    dnsPrefix: {{ .dnsPrefix }}
    automaticChannelUpgrade: {{ .automaticChannelUpgrade }}
    httpApplicationRoutingEnabled: {{ .httpApplicationRoutingEnabled }}
    runCommandEnabled: {{ .runCommandEnabled }}
    {{- if .identity }}
    identity:
      {{- range .identity }}
      - identityIds:
          {{- range .identityIds }}
          - {{ . }}
          {{- end }}
        type: {{ .type }}
      {{- end }}
    {{- end }}
    networkProfile:
      {{- range .networkProfile }}
      - dnsServiceIp: {{ .dnsServiceIp }}
        networkMode: {{ .networkMode | quote }}
        networkPlugin: {{ .networkPlugin }}
        networkPolicy: {{ .networkPolicy }}
        serviceCidrs:
          {{- range .serviceCidrs }}
          - {{ . }}
          {{- end }}
      {{- end }}
    defaultNodePool:
      {{- range .defaultNodePool }}
      - name: {{ .name }}
        nodeCount: {{ .nodeCount }}
        vmSize: {{ .vmSize }}
        temporaryNameForRotation: {{ .temporaryNameForRotation }}
        type: {{ .type }}
        vnetSubnetId: {{ .vnetSubnetId }}
        maxCount: {{ .maxCount }}
        minCount: {{ .minCount }}
        maxPods: {{ .maxPods }}
        enableAutoScaling: {{ .enableAutoScaling }}
        upgradeSettings:
          {{- range .upgradeSettings }}
          - maxSurge: {{ .maxSurge }}
          {{- end }}
        zones:
          {{- range .zones }}
          - "{{ . }}"
          {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
