apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mdp-poc-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: "./managed-templates"
      sourceRef:
        kind: GitRepository
        name: fluxcd-crossplane-idp
        namespace: flux-system
  interval: 1m0s
  releaseName: mdp-poc-release
  valuesFrom:
    - kind: ConfigMap
      name: mdp-poc-values
      valuesKey: mdp-poc-values.yaml
