---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: azure-secret
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB2fUHkJMocz+/7uZbLmeftAQ2wgMWFE1xTj0iyBv5ThcIpD2L/ebe3XIlTAeuFFRx9DgtiXR70pzF87DUbXlvKfZVINbzHCTRHJoMnhYtvzeGYyL6kD5Du4DAoH/oJgLz710CMfKU9WdkvGRhEaV239QhvyYfTtCWb7x65rGjZyQ3ZCGQ2iCAcBmsuu9jWpa0wu8Q5pORCI76XFOS1sz6qL5x39mrAD827EVHtTZrhZc+7ZVo9MmiFEBGpx7GbKD2XdIxej062lGGU6vOa3wcKUosyZbXsXBZqKRY9OIeJuu0XIBUNerqyp9pjos/3lseO1EVqwaq/ItjDr8PcQTZJIir/Oj9hz927jskV1QnCddSUiaXyh9v3I1viZiL1os5+eBdmUqGXOITXwOOdwQpN9XeVooKoPmvFzK8hxKHhi9Ab2fGEMeXbDHaKGdLJYUojlw/MGtUg9b9eTd4dOnUtRcwt8YTtcSRPxRGvJvH3sQaiEBEbrOp0Iz1gM/w/KiD5wv++83VEpymfag6vXsIN6LvtVhx1fsKFnsoZOUsFt8i6Ol+/TmavuSMen0Lg8MV2ybg+DL453bNBzTlMOhuA+Q2LGJXp/88BwL7Hqmk0UlIf7xlFA2lEVEL5aBjvUMLdsKYhDaeYB0/SsEGPXtCeWsvAJZ8Il9SUCy4pqagxFJlp1ODU8+DXP61eOENxStIFaaKH6fZPiHYuSMWVESbql2f6hA3Q1rhGfkbo3h5aVd1ZcDvNd9KTWB7I7qQGo+AEdQDXJg51dMgcDQa+zq5yg3V0d02n5OIQCF1yYzYSZhXW+R5hlplwHrmPQSZHekwiJHkOOmfqAgEf1al2j89AF9/rkozPLl6i8O6e67CNNoCifuaIqYpQ8T9RakD10/3O/mz16JI14AYp6N88kgscE98VZox3W9uA1/NRhJx65yuzkfbwJYuQDlMW4E/grB94WHMys2p6NetFCQMOSoHLgRKlrEXjExRuDqN4KAbSkGcRCDj1SrOsxEp8YstG3kwySFfs5W5XQh9p9aZDB1fYlbrisPWWOFoV1hnr+d3r9NvWHjECbM45z25+0xJ58TY8rUaqkw8CR9SPanjhyt4o9WtWcYsE2tLX0ngviBJz8K8BpilE6SWkKkL4CbgQvILN59uWU4HRU6rXCO2uAVYwl9+dYEslENOZInI76y7iZoSu+dUiJTi/hVRspEDiQYIsRWItB8H3RuMInmeXaUGJTSEDAVkWOIGqt5xTNwr0SdHSBKcQK77tdYmNjwiGr6EX1k41VB1+Lk1uVABV3ztfnwu3Ap68bFxJxoa43er+Qz2JSEZbefH/bA394tn49DZReI//ul6Q0mmsNB5WpNYww7qW7/NZYmwiQJwGXIoqrAo7NO9775AZJ5lu7QnFrWupexbjkqXg8N4oli9kFTFVSuFMEFfzPqW4YwDBpSkbiTEhsHtIzh8vD9RTMS0ibGaXK0XEhD43nhLA2+0AYZ6ABDcfzDJYvbXk0TrApmJHusXUtobeN2ZTn5WEDjWg3zoxKRxqWw==
  template:
    metadata:
      creationTimestamp: null
      name: azure-secret
      namespace: crossplane-system
