apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: mesh-cluster
spec:
  providerConfigRef:
    name: kishore-azure-config
  forProvider:
    location: West Europe
    resourceGroupName: mdp-poc
    kubernetesVersion: 1.28.9
    privateClusterEnabled: true
    dnsPrefix: mesh-aks
    automaticChannelUpgrade: stable
    httpApplicationRoutingEnabled: true
    runCommandEnabled: true
    identity:
      - identityIds:
          - "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourcegroups/mdp-poc/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-identity"
        type: UserAssigned
    networkProfile:
      - dnsServiceIp: "10.0.0.10"
        networkMode: ""
        networkPlugin: "azure"
        networkPolicy: "calico"
        serviceCidrs:
          - "10.0.0.0/16"
    defaultNodePool:
      - name: default
        nodeCount: 3
        minCount: 1
        maxCount: 5
        maxPods: 250
        vmSize: Standard_DS2_v2
        enableAutoScaling: true
        temporaryNameForRotation: "temp-nodepool"
        type: "VirtualMachineScaleSets"
        upgradeSettings:
          - maxSurge: "1"
        vnetSubnetId: "/subscriptions/1947901f-c34b-4ff0-98e7-0f0acf01b5a7/resourceGroups/mdp-poc/providers/Microsoft.Network/virtualNetworks/k8s-vnet/subnets/k8s-subnet"
        zones:
          - "1"
          - "2"
          - "3"
